### PR TITLE
Documentation/read me

### PR DESCRIPTION
**Pull request by AbirAahammed**
This pull request is made to address the issue raised by @hocky0414 on behalf of updated readme requirement for sprint 1.

### CODE REVIEW

**Comment by AbirAahammed** [comment]
Please don't close the pull request until everyone has reviewed it

**Review by ConnorGehman — APPROVED** [review]
Theses changes look good. Firebase noted.

**Review by hocky0414 — APPROVED** [review]
looks good

**Comment by h-connor** [comment]
Looks fine.

**Review by h-connor — APPROVED** [review]

**Review by CBM6 — APPROVED** [review]
Looks good to me

**Pull request merged**
